#!/bin/sh
#
# Run Dexter forever:
#   CONFIG=pi_config nohup ./run < /dev/null >> dexter.log 2>&1 &
# changing 'pi_config' to the name of your config file, if need be.
while true
do
    # Unset the DISPLAY else PyGame can crash. Set the terminal to dumb so that
    # PyGame doesn't use ncurses to then mess the terminal up. When running from
    # systemd the TERM will not be set and that breaks PyGame too.
    env -u DISPLAY TERM=dumb ./dexter.py -c ${CONFIG:-pi_config}
done
